### ISSUE TITLE
Berkshelf could not find compatible versions for cookbook 'mysql-test-schema':

### ISSUE THREAD

**Issue by akuzminsky** [twindb/twindb-agent-testing#2]
```
-----> Destroying <server55-default-centos-511>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <server55-default-centos-511> destroyed.
       Finished destroying <server55-default-centos-511> (0m3.80s).
rake aborted!
Kitchen::ActionFailed: Failed to complete #converge action: [Berkshelf could not find compatible versions for cookbook 'mysql-test-schema':
  In Berksfile:
    mysql-test-schema (= 0.2.1)

  In Berksfile.lock:
    mysql-test-schema (0.2.0)

Try running `berks update mysql-test-schema`, which will try to find 'mysql-test-schema' matching '= 0.2.1'.]/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/lockfile.rb:396:in `block in reduce!'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/lockfile.rb:384:in `each'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/lockfile.rb:384:in `reduce!'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/installer.rb:32:in `run'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:374:in `install'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:583:in `block in vendor'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/berkshelf-3.3.0/lib/berkshelf/berksfile.rb:581:in `vendor'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/berkshelf.rb:68:in `block in resolve'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/berkshelf.rb:64:in `resolve'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/common_sandbox.rb:286:in `block in resolve_with_berkshelf'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/common_sandbox.rb:285:in `synchronize'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/common_sandbox.rb:285:in `resolve_with_berkshelf'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/common_sandbox.rb:251:in `prepare_cookbooks'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef/common_sandbox.rb:50:in `populate'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef_base.rb:100:in `create_sandbox'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/chef_zero.rb:52:in `create_sandbox'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:61:in `call'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:189:in `block in test'
/Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
/Users/aleks/src/twindb-agent-testing/Rakefile:88:in `block (3 levels) in <top (required)>'
/Users/aleks/src/twindb-agent-testing/Rakefile:87:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => integration:vagrant
```

**Comment by akuzminsky** [comment]
Running `./bin/rake default`

**Comment by ovaistariq** [comment]
Can you delete the file 'Berksfile.lock' and then try again

**Comment by akuzminsky** [comment]
recent changes fixed the issue
