### ISSUE TITLE
fails to install packagecloud_repo

### ISSUE THREAD

**Issue by akuzminsky** [twindb/twindb-agent-testing#5]
```
W, [2015-09-19T10:11:53.923443 #4540]  WARN -- server55-default-centos-6: WARN: aws_access_key_id has been deprecated, please use ENV['AWS_ACCESS_KEY_ID'] or ~/.aws/credentials.  See the README for more details
W, [2015-09-19T10:11:53.923545 #4540]  WARN -- server55-default-centos-6: WARN: aws_secret_access_key has been deprecated, please use ENV['AWS_SECRET_ACCESS_KEY'] or ~/.aws/credentials.  See the README for more details
I, [2015-09-19T10:11:54.230903 #4540]  INFO -- server55-default-centos-6: -----> Cleaning up any prior instances of <server55-default-centos-6>
I, [2015-09-19T10:11:54.231414 #4540]  INFO -- server55-default-centos-6: -----> Destroying <server55-default-centos-6>...
I, [2015-09-19T10:11:54.233003 #4540]  INFO -- server55-default-centos-6: Finished destroying <server55-default-centos-6> (0m0.00s).
I, [2015-09-19T10:11:54.233344 #4540]  INFO -- server55-default-centos-6: -----> Testing <server55-default-centos-6>
I, [2015-09-19T10:11:54.233417 #4540]  INFO -- server55-default-centos-6: -----> Creating <server55-default-centos-6>...
I, [2015-09-19T10:11:54.233809 #4540]  INFO -- server55-default-centos-6: If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

I, [2015-09-19T10:11:55.988499 #4540]  INFO -- server55-default-centos-6: Overriding root device [/dev/sda1] from image [ami-1bcad42b]
I, [2015-09-19T10:11:57.141391 #4540]  INFO -- server55-default-centos-6: Instance <i-3b0860e0> requested.
I, [2015-09-19T10:11:57.593947 #4540]  INFO -- server55-default-centos-6: EC2 instance <i-3b0860e0> created.
I, [2015-09-19T10:11:57.594069 #4540]  INFO -- server55-default-centos-6: Waited 0/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:03.154244 #4540]  INFO -- server55-default-centos-6: Waited 5/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:08.710042 #4540]  INFO -- server55-default-centos-6: Waited 10/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:14.279895 #4540]  INFO -- server55-default-centos-6: Waited 15/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:19.812175 #4540]  INFO -- server55-default-centos-6: Waited 20/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:25.305596 #4540]  INFO -- server55-default-centos-6: Waited 25/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:30.883343 #4540]  INFO -- server55-default-centos-6: Waited 30/300s for instance <i-3b0860e0> to become ready.
I, [2015-09-19T10:12:31.600096 #4540]  INFO -- server55-default-centos-6: EC2 instance <i-3b0860e0> ready.
I, [2015-09-19T10:12:41.606476 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:12:54.608480 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:13:07.610363 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:13:10.664560 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:13:13.718286 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:13:17.522925 #4540]  INFO -- server55-default-centos-6: Waiting for SSH service on ec2-52-10-90-137.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
I, [2015-09-19T10:13:21.797093 #4540]  INFO -- server55-default-centos-6: [SSH] Established
I, [2015-09-19T10:13:22.227384 #4540]  INFO -- server55-default-centos-6: Finished creating <server55-default-centos-6> (1m27.99s).
I, [2015-09-19T10:13:22.228104 #4540]  INFO -- server55-default-centos-6: -----> Converging <server55-default-centos-6>...
I, [2015-09-19T10:13:22.228601 #4540]  INFO -- server55-default-centos-6: Preparing files for transfer
I, [2015-09-19T10:13:22.228668 #4540]  INFO -- server55-default-centos-6: Preparing dna.json
I, [2015-09-19T10:13:22.229049 #4540]  INFO -- server55-default-centos-6: Resolving cookbook dependencies with Berkshelf 3.3.0...
I, [2015-09-19T10:13:23.078087 #4540]  INFO -- server55-default-centos-6: Removing non-cookbook files before transfer
I, [2015-09-19T10:13:23.095549 #4540]  INFO -- server55-default-centos-6: Preparing validation.pem
I, [2015-09-19T10:13:23.096010 #4540]  INFO -- server55-default-centos-6: Preparing client.rb
I, [2015-09-19T10:13:23.212743 #4540]  INFO -- server55-default-centos-6: Transferring files to <server55-default-centos-6>
I, [2015-09-19T10:15:05.753261 #4540]  INFO -- server55-default-centos-6: Starting Chef Client, version 12.4.1
I, [2015-09-19T10:15:09.645383 #4540]  INFO -- server55-default-centos-6: Creating a new client identity for server55-default-centos-6 using the validator key.
I, [2015-09-19T10:15:09.841597 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
I, [2015-09-19T10:15:09.845589 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
I, [2015-09-19T10:15:09.845698 #4540]  INFO -- server55-default-centos-6: resolving cookbooks for run list: ["test-helper::default", "twindb-agent-dev::default"]
I, [2015-09-19T10:15:09.845848 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:09+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
I, [2015-09-19T10:15:11.349066 #4540]  INFO -- server55-default-centos-6: Synchronizing Cookbooks:
I, [2015-09-19T10:15:11.766241 #4540]  INFO -- server55-default-centos-6:   - test-helper
I, [2015-09-19T10:15:12.106224 #4540]  INFO -- server55-default-centos-6:   - twindb-agent-dev
I, [2015-09-19T10:15:12.475696 #4540]  INFO -- server55-default-centos-6:   - build-essential
I, [2015-09-19T10:15:12.581770 #4540]  INFO -- server55-default-centos-6:   - packagecloud
I, [2015-09-19T10:15:12.667836 #4540]  INFO -- server55-default-centos-6:   - gem_specific_install
I, [2015-09-19T10:15:12.711217 #4540]  INFO -- server55-default-centos-6:   - yum-epel
I, [2015-09-19T10:15:13.212415 #4540]  INFO -- server55-default-centos-6:   - git
I, [2015-09-19T10:15:13.418349 #4540]  INFO -- server55-default-centos-6:   - yum
I, [2015-09-19T10:15:13.590522 #4540]  INFO -- server55-default-centos-6:   - dmg
I, [2015-09-19T10:15:14.756029 #4540]  INFO -- server55-default-centos-6:   - windows
I, [2015-09-19T10:15:14.778624 #4540]  INFO -- server55-default-centos-6:   - chef_handler
I, [2015-09-19T10:15:14.778667 #4540]  INFO -- server55-default-centos-6: Compiling Cookbooks...
I, [2015-09-19T10:15:14.833689 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:14+00:00] WARN: chef_gem[activesupport] chef_gem compile_time installation is deprecated
I, [2015-09-19T10:15:14.833739 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:14+00:00] WARN: chef_gem[activesupport] Please set `compile_time false` on the resource to use the new behavior.
I, [2015-09-19T10:15:14.833757 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:14+00:00] WARN: chef_gem[activesupport] or set `compile_time true` on the resource if compile_time behavior is required.
I, [2015-09-19T10:15:14.833772 #4540]  INFO -- server55-default-centos-6: Recipe: test-helper::default
I, [2015-09-19T10:15:16.258861 #4540]  INFO -- server55-default-centos-6:  (up to date)
I, [2015-09-19T10:15:16.361994 #4540]  INFO -- server55-default-centos-6:   Converging 11 resources
I, [2015-09-19T10:15:16.369399 #4540]  INFO -- server55-default-centos-6:  (up to date)
I, [2015-09-19T10:15:16.369439 #4540]  INFO -- server55-default-centos-6:   * directory[/tmp/serverspec] action create
I, [2015-09-19T10:15:16.507000 #4540]  INFO -- server55-default-centos-6: 
I, [2015-09-19T10:15:16.507053 #4540]  INFO -- server55-default-centos-6:     - restore selinux security context
I, [2015-09-19T10:15:16.507071 #4540]  INFO -- server55-default-centos-6:   * file[/tmp/serverspec/node.json] action create
I, [2015-09-19T10:15:16.507086 #4540]  INFO -- server55-default-centos-6:     - create new file /tmp/serverspec/node.json
I, [2015-09-19T10:15:16.507099 #4540]  INFO -- server55-default-centos-6:     - change mode from '' to '0400'
I, [2015-09-19T10:15:16.611618 #4540]  INFO -- server55-default-centos-6: 
I, [2015-09-19T10:15:16.611672 #4540]  INFO -- server55-default-centos-6:     - restore selinux security context
I, [2015-09-19T10:15:16.611696 #4540]  INFO -- server55-default-centos-6:   * log[Dumping attributes to '/tmp/serverspec/node.json.] action write
I, [2015-09-19T10:15:16.611711 #4540]  INFO -- server55-default-centos-6:   
I, [2015-09-19T10:15:16.723103 #4540]  INFO -- server55-default-centos-6: 
I, [2015-09-19T10:15:16.723157 #4540]  INFO -- server55-default-centos-6:     - execute the ruby block dump_node_attributes
I, [2015-09-19T10:15:16.723175 #4540]  INFO -- server55-default-centos-6: Recipe: twindb-agent-dev::default
I, [2015-09-19T10:15:17.384867 #4540]  INFO -- server55-default-centos-6: 
I, [2015-09-19T10:15:17.384917 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.384937 #4540]  INFO -- server55-default-centos-6:     ================================================================================
I, [2015-09-19T10:15:17.384952 #4540]  INFO -- server55-default-centos-6:     Error executing action `add` on resource 'packagecloud_repo[/main/]'
I, [2015-09-19T10:15:17.384965 #4540]  INFO -- server55-default-centos-6:     ================================================================================
I, [2015-09-19T10:15:17.384978 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.384990 #4540]  INFO -- server55-default-centos-6:     RuntimeError
I, [2015-09-19T10:15:17.385002 #4540]  INFO -- server55-default-centos-6:     ------------
I, [2015-09-19T10:15:17.385015 #4540]  INFO -- server55-default-centos-6:     #<Net::HTTPNotFound 404 Not Found readbody=true>
I, [2015-09-19T10:15:17.385027 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385039 #4540]  INFO -- server55-default-centos-6:     Cookbook Trace:
I, [2015-09-19T10:15:17.385051 #4540]  INFO -- server55-default-centos-6:     ---------------
I, [2015-09-19T10:15:17.385063 #4540]  INFO -- server55-default-centos-6:     /tmp/kitchen/cache/cookbooks/packagecloud/libraries/helper.rb:20:in `get'
I, [2015-09-19T10:15:17.385075 #4540]  INFO -- server55-default-centos-6:     /tmp/kitchen/cache/cookbooks/packagecloud/providers/repo.rb:69:in `install_rpm'
I, [2015-09-19T10:15:17.385088 #4540]  INFO -- server55-default-centos-6:     /tmp/kitchen/cache/cookbooks/packagecloud/providers/repo.rb:12:in `block in class_from_file'
I, [2015-09-19T10:15:17.385100 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385113 #4540]  INFO -- server55-default-centos-6:     Resource Declaration:
I, [2015-09-19T10:15:17.385126 #4540]  INFO -- server55-default-centos-6:     ---------------------
I, [2015-09-19T10:15:17.385138 #4540]  INFO -- server55-default-centos-6:     # In /tmp/kitchen/cache/cookbooks/twindb-agent-dev/recipes/default.rb
I, [2015-09-19T10:15:17.385151 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385163 #4540]  INFO -- server55-default-centos-6:      11: packagecloud_repo repository do
I, [2015-09-19T10:15:17.385176 #4540]  INFO -- server55-default-centos-6:      12:   case node["platform_family"]
I, [2015-09-19T10:15:17.385188 #4540]  INFO -- server55-default-centos-6:      13:   when "debian"
I, [2015-09-19T10:15:17.385201 #4540]  INFO -- server55-default-centos-6:      14:     type "deb"
I, [2015-09-19T10:15:17.385213 #4540]  INFO -- server55-default-centos-6:      15:   when "rhel", "fedora"
I, [2015-09-19T10:15:17.385238 #4540]  INFO -- server55-default-centos-6:      16:     type "rpm"
I, [2015-09-19T10:15:17.385253 #4540]  INFO -- server55-default-centos-6:      17:     priority 9
I, [2015-09-19T10:15:17.385265 #4540]  INFO -- server55-default-centos-6:      18:   end
I, [2015-09-19T10:15:17.385278 #4540]  INFO -- server55-default-centos-6:      19: end
I, [2015-09-19T10:15:17.385290 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385303 #4540]  INFO -- server55-default-centos-6:     Compiled Resource:
I, [2015-09-19T10:15:17.385315 #4540]  INFO -- server55-default-centos-6:     ------------------
I, [2015-09-19T10:15:17.385328 #4540]  INFO -- server55-default-centos-6:     # Declared in /tmp/kitchen/cache/cookbooks/twindb-agent-dev/recipes/default.rb:11:in `from_file'
I, [2015-09-19T10:15:17.385340 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385351 #4540]  INFO -- server55-default-centos-6:     packagecloud_repo("/main/") do
I, [2015-09-19T10:15:17.385756 #4540]  INFO -- server55-default-centos-6:   action [:add]
I, [2015-09-19T10:15:17.385780 #4540]  INFO -- server55-default-centos-6:       retries 0
I, [2015-09-19T10:15:17.385794 #4540]  INFO -- server55-default-centos-6:       retry_delay 2
I, [2015-09-19T10:15:17.385808 #4540]  INFO -- server55-default-centos-6:       default_guard_interpreter :default
I, [2015-09-19T10:15:17.385821 #4540]  INFO -- server55-default-centos-6:       declared_type :packagecloud_repo
I, [2015-09-19T10:15:17.385834 #4540]  INFO -- server55-default-centos-6:       cookbook_name "twindb-agent-dev"
I, [2015-09-19T10:15:17.385846 #4540]  INFO -- server55-default-centos-6:       recipe_name "default"
I, [2015-09-19T10:15:17.385859 #4540]  INFO -- server55-default-centos-6:       type "rpm"
I, [2015-09-19T10:15:17.385873 #4540]  INFO -- server55-default-centos-6:       priority 9
I, [2015-09-19T10:15:17.385886 #4540]  INFO -- server55-default-centos-6:       base_url "https://packagecloud.io"
I, [2015-09-19T10:15:17.385898 #4540]  INFO -- server55-default-centos-6:       repository "/main/"
I, [2015-09-19T10:15:17.385911 #4540]  INFO -- server55-default-centos-6:     end
I, [2015-09-19T10:15:17.385923 #4540]  INFO -- server55-default-centos-6:     
I, [2015-09-19T10:15:17.385935 #4540]  INFO -- server55-default-centos-6: 
I, [2015-09-19T10:15:17.385948 #4540]  INFO -- server55-default-centos-6: Running handlers:
I, [2015-09-19T10:15:17.385960 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:16+00:00] ERROR: Running exception handlers
I, [2015-09-19T10:15:17.385972 #4540]  INFO -- server55-default-centos-6: Running handlers complete
I, [2015-09-19T10:15:17.386301 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:16+00:00] ERROR: Exception handlers complete
I, [2015-09-19T10:15:17.386335 #4540]  INFO -- server55-default-centos-6: Chef Client failed. 4 resources updated in 11.689991659 seconds
I, [2015-09-19T10:15:17.428366 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:16+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
I, [2015-09-19T10:15:17.428415 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:16+00:00] ERROR: packagecloud_repo[/main/] (twindb-agent-dev::default line 11) had an error: RuntimeError: #<Net::HTTPNotFound 404 Not Found readbody=true>
I, [2015-09-19T10:15:17.733771 #4540]  INFO -- server55-default-centos-6: [2015-09-19T17:15:16+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
E, [2015-09-19T10:15:17.759431 #4540] ERROR -- server55-default-centos-6: Converge failed on instance <server55-default-centos-6>.
E, [2015-09-19T10:15:17.759565 #4540] ERROR -- server55-default-centos-6: ------Exception-------
E, [2015-09-19T10:15:17.759587 #4540] ERROR -- server55-default-centos-6: Class: Kitchen::ActionFailed
E, [2015-09-19T10:15:17.759600 #4540] ERROR -- server55-default-centos-6: Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
E, [2015-09-19T10:15:17.759624 #4540] ERROR -- server55-default-centos-6: ---Nested Exception---
E, [2015-09-19T10:15:17.759637 #4540] ERROR -- server55-default-centos-6: Class: Kitchen::Transport::SshFailed
E, [2015-09-19T10:15:17.759648 #4540] ERROR -- server55-default-centos-6: Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
E, [2015-09-19T10:15:17.759660 #4540] ERROR -- server55-default-centos-6: ------Backtrace-------
E, [2015-09-19T10:15:17.759670 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
E, [2015-09-19T10:15:17.759689 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
E, [2015-09-19T10:15:17.759704 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2015-09-19T10:15:17.759715 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2015-09-19T10:15:17.759725 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-09-19T10:15:17.759736 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-09-19T10:15:17.759747 #4540] ERROR -- server55-default-centos-6: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2015-09-19T10:15:17.759757 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-09-19T10:15:17.759768 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
E, [2015-09-19T10:15:17.759778 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-09-19T10:15:17.759789 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-09-19T10:15:17.759799 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-09-19T10:15:17.759810 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
E, [2015-09-19T10:15:17.759820 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-09-19T10:15:17.759831 #4540] ERROR -- server55-default-centos-6: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2015-09-19T10:15:17.759841 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
E, [2015-09-19T10:15:17.759852 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-09-19T10:15:17.759869 #4540] ERROR -- server55-default-centos-6: /Users/aleks/src/twindb-agent-testing/.bundle/ruby/2.0.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-09-19T10:15:17.759882 #4540] ERROR -- server55-default-centos-6: ----------------------
 ```

**Comment by ovaistariq** [comment]
Fixed.
